name: C++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ -O2 -std=gnu++17 -o WordleCpp src/cpp/*.cpp src/cpp/**/*.cpp -Isrc/include
      working-directory: WordleCpp
