name: C++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ -O3 -std=gnu++17 -fpermissive -o WordleCpp src/*.cpp src/**/*.cpp -Iinclude
      working-directory: WordleCpp
