name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build
      run: cargo build --verbose
      working-directory: wordle-rs
    - name: Run tests
      run: cargo test --verbose
      working-directory: wordle-rs
